return {
	require("config.plug.lsp"),
	require("config.plug.hop"),
	require("config.plug.compe"),
	require("config.plug.lualine"),
	require("config.plug.lspkind"),
	require("config.plug.luasnip"),
	require("config.plug.nvimtree"),
	require("config.plug.gitsigns"),
	require("config.plug.dashboard"),
	require("config.plug.autopairs"),
	require("config.plug.bufferline"),
	require("config.plug.nvim-comment"),
	require("config.plug.nvim-colorizer"),
	require("config.plug.nvim-treesitter"),
}
